# Name of the Spring Boot application
spring.application.name=chat-model
spring.ai.bedrock.aws.region=${AWS_REGION}
spring.ai.bedrock.aws.access-key=${AWS_ACCESS_KEY}
spring.ai.bedrock.aws.secret-key=${AWS_SECRET_KEY}
spring.ai.model.chat=bedrock-converse

# ----------- MODEL CONFIG -----------
# Using Claude 3 Sonnet via AWS Bedrock Converse API
spring.ai.bedrock.converse.chat.options.model=anthropic.claude-3-sonnet-20240229-v1:0
spring.ai.bedrock.converse.chat.options.max-tokens=800

logging.level.org.springframework.ai=DEBUG